server:
  port: 8080

spring:
  application:
    name: fresh-food-traceability
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fresh_food_db?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 123456 # 请修改为你的数据库密码
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true # 开启下划线转驼峰
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 开启SQL日志打印
  global-config:
    db-config:
      id-type: auto # 主键自增

app:
  h5-base-url: http://172.20.10.5:3000 # 请改成固定可被手机访问的 H5 地址或域名
